INSERT INTO CUSTOMERS (CID, NAME) VALUES
(1, 'John Doe'),
(2, 'Jane Smith'),
(3, 'Michael Johnson'),
(4, 'Emily Brown'),
(5, 'David Lee'),
(6, 'Lisa Davis'),
(7, 'Christopher Wilson'),
(8, 'Sarah Martin'),
(9, 'Ryan Thompson'),
(10, 'Olivia Clark'),
(11, 'Megan Smith'),
(12, 'Ethan Lee'),
(13, 'Sophia Chen'),
(14, 'Isabella Wong'),
(15, 'William Kim');
