INSERT INTO BOOKS (PUBID, TITLE) VALUES
  (1, 'To Kill a Mockingbird'),
  (2, 'The Great Gatsby'),
  (3, '1984'),
  (4, 'Pride and Prejudice'),
  (5, 'Harry Potter and the Deathly Hallows'),
  (6, 'Jane Eyre'),
  (7, 'The Catcher in the Rye'),
  (8, 'The Lord of the Rings'),
  (9, 'Animal Farm'),
  (10, 'Wuthering Heights'),
  (11, 'Brave New World'),
  (12, 'The Picture of Dorian Gray'),
  (13, 'The Hobbit'),
  (14, 'Gone with the Wind'),
  (15, 'Emma'),
  (16, "Harry Potter and the Philosopher's Stone"),
  (17, 'The Adventures of Huckleberry Finn'),
  (18, 'Sense and Sensibility'),
  (19, 'Harry Potter and the Chamber of Secrets'),
  (20, 'Harry Porter Finale');
