SELECT p.PUBID, pb.TITLE, AVG(DATEDIFF(day, o.DATE_TIME, io.DELIVERY_DATE)) AS AVG_TIME
FROM PUBLICATION p
JOIN (
    SELECT b.PUBID, b.TITLE, s.STOCKID
    FROM BOOKS b
    JOIN STOCKS_IN_BOOKSTORE s ON b.PUBID = s.PUBID
    UNION
    SELECT m.PUBID, m.TITLE, s.STOCKID
    FROM MAGAZINES m
    JOIN STOCKS_IN_BOOKSTORE s ON m.PUBID = s.PUBID
    ) AS pb ON p.PUBID = pb.PUBID
JOIN STOCKS_IN_BOOKSTORE s ON pb.STOCKID = s.STOCKID
JOIN ITEMS_IN_ORDERS io ON s.STOCKID = io.STOCKID
JOIN ORDERS o ON io.ORDERID = o.ORDERID
WHERE io.DELIVERY_DATE IS NOT NULL
AND o.DATE_TIME >= '2022-06-01' AND o.DATE_TIME < '2022-07-01'
GROUP BY p.PUBID, pb.TITLE
ORDER BY AVG_TIME;
