SELECT E.NAME, AVG(DATEDIFF(MINUTE, C.FILLED_DATE_TIME, C.HANDLED_DATE_TIME)) AS LATENCY
FROM COMPLAINTS C
JOIN EMPLOYEES E ON C.EID = E.EID
GROUP BY E.NAME
HAVING AVG(DATEDIFF(MINUTE, C.FILLED_DATE_TIME, C.HANDLED_DATE_TIME)) IN (
  SELECT MIN(avg_latency)
  FROM (
    SELECT AVG(DATEDIFF(MINUTE, C.FILLED_DATE_TIME, C.HANDLED_DATE_TIME)) AS avg_latency
    FROM COMPLAINTS C
    JOIN EMPLOYEES E ON C.EID = E.EID
    GROUP BY E.NAME
  ) AS min_latencies
)
