SELECT s.PUBID, pb.TITLE, AVG(io.RATING) AS AVG_RATING
FROM STOCKS_IN_BOOKSTORE s
JOIN ITEMS_IN_ORDERS io ON s.STOCKID = io.STOCKID
JOIN ORDERS o ON io.ORDERID = o.ORDERID
JOIN (
    SELECT b.PUBID, b.TITLE, s.STOCKID
    FROM BOOKS b
    JOIN STOCKS_IN_BOOKSTORE s ON b.PUBID = s.PUBID
    UNION
    SELECT m.PUBID, m.TITLE, s.STOCKID
    FROM MAGAZINES m
    JOIN STOCKS_IN_BOOKSTORE s ON m.PUBID = s.PUBID
) AS pb ON s.STOCKID = pb.STOCKID
WHERE io.DATE_TIME >= '2022-08-01' AND io.DATE_TIME < '2022-09-01'
GROUP BY s.PUBID, pb.TITLE
HAVING EXISTS (
  SELECT *
    FROM ITEMS_IN_ORDERS io2
    JOIN STOCKS_IN_BOOKSTORE s2 ON io2.STOCKID = s2.STOCKID
    WHERE s2.PUBID = s.PUBID AND io2.RATING = 5
    GROUP BY s2.PUBID
    HAVING COUNT(*) >= 10
)
ORDER BY AVG_RATING DESC;
