SELECT TOP 3 p.PUBID, COUNT(*) AS num_purchases
FROM PUBLICATION p
JOIN STOCKS_IN_BOOKSTORE s ON p.PUBID = s.PUBID
JOIN ITEMS_IN_ORDERS io ON s.STOCKID = io.STOCKID
WHERE MONTH(io.DATE_TIME) = 8
AND p.PUBID NOT IN (
    SELECT DISTINCT s.PUBID
    FROM ITEMS_IN_ORDERS io
    JOIN STOCKS_IN_BOOKSTORE s ON io.STOCKID = s.STOCKID
    WHERE MONTH(io.DATE_TIME) = 7
)
GROUP BY p.PUBID
ORDER BY num_purchases DESC
