SELECT TOP 3 p.PUBID, COUNT(*) AS num_purchases
FROM PUBLICATION p
JOIN STOCKS_IN_BOOKSTORE s ON p.PUBID = s.PUBID
JOIN ITEMS_IN_ORDERS io ON s.STOCKID = io.STOCKID
JOIN ORDERS o ON o.ORDERID = io.ORDERID
WHERE o.DATE_TIME >= '2022-08-01' AND o.DATE_TIME < '2022-09-01'
AND p.PUBID NOT IN (
	SELECT DISTINCT s.PUBID
	FROM ORDERS o
	JOIN ITEMS_IN_ORDERS io ON io.ORDERID = o.ORDERID
	JOIN STOCKS_IN_BOOKSTORE s ON io.STOCKID = s.STOCKID
	WHERE o.DATE_TIME >= '2022-07-01' AND o.DATE_TIME < '2022-08-01'
)
GROUP BY p.PUBID
ORDER BY num_purchases DESC;
