SELECT AVG(PRICE) AS AVERAGE_PRICE
FROM PRICE_HISTORY PH
JOIN STOCKS_IN_BOOKSTORE SB ON PH.STOCKID = SB.STOCKID
JOIN BOOKS B ON SB.PUBID = B.PUBID
WHERE B.TITLE = 'Harry Porter Finale'
    AND PH.START_DATE >= '2022-08-01'
    AND PH.END_DATE <= '2022-08-31';
