SELECT TOP 1 PUBID, MAX(STOCK_PRICE) AS MAX_PRICE
FROM STOCKS_IN_BOOKSTORE
WHERE PUBID IN (
    SELECT s.PUBID
    FROM ITEMS_IN_ORDERS io
    JOIN STOCKS_IN_BOOKSTORE s ON io.STOCKID = s.STOCKID
    WHERE io.CID IN (
        SELECT TOP 1 c.CID
        FROM COMPLAINTS c
        GROUP BY c.CID
        ORDER BY COUNT(*) DESC
    )
)
GROUP BY PUBID;
