SELECT s.PUBID, b.TITLE, AVG(io.RATING) AS AVG_RATING
FROM STOCKS_IN_BOOKSTORE s
JOIN ITEMS_IN_ORDERS io ON s.STOCKID = io.STOCKID
JOIN ORDERS o ON io.ORDERID = o.ORDERID
LEFT JOIN BOOKS b ON s.PUBID = b.PUBID
LEFT JOIN MAGAZINES m ON s.PUBID = m.PUBID
LEFT JOIN PUBLICATION p ON s.PUBID = p.PUBID
WHERE io.DATE_TIME >= '2022-08-01' AND io.DATE_TIME < '2022-09-01'
GROUP BY s.PUBID, b.TITLE, m.TITLE
HAVING EXISTS (
  SELECT *
    FROM ITEMS_IN_ORDERS io2
    JOIN STOCKS_IN_BOOKSTORE s2 ON io2.STOCKID = s2.STOCKID
    WHERE s2.PUBID = s.PUBID AND io2.RATING = 5
    GROUP BY s2.PUBID
    HAVING COUNT(*) >= 10
)
ORDER BY AVG_RATING DESC;
